# Generated by Django 4.2.7 on 2024-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
